export const SHIP_CATALOG = [
  { id: "aegis-avenger-titan", name: "Aegis Avenger Titan", manufacturer: "Aegis Dynamics", role: "Light Freight", size: "Small" },
  { id: "aegis-avenger-stalker", name: "Aegis Avenger Stalker", manufacturer: "Aegis Dynamics", role: "Interdiction", size: "Small" },
  { id: "aegis-avenger-warlock", name: "Aegis Avenger Warlock", manufacturer: "Aegis Dynamics", role: "EMP", size: "Small" },
  { id: "aegis-eclipse", name: "Aegis Eclipse", manufacturer: "Aegis Dynamics", role: "Stealth Bomber", size: "Medium" },
  { id: "aegis-gladius", name: "Aegis Gladius", manufacturer: "Aegis Dynamics", role: "Light Fighter", size: "Small" },
  { id: "aegis-hammerhead", name: "Aegis Hammerhead", manufacturer: "Aegis Dynamics", role: "Patrol", size: "Capital" },
  { id: "aegis-reclaimer", name: "Aegis Reclaimer", manufacturer: "Aegis Dynamics", role: "Heavy Salvage", size: "Capital" },
  { id: "aegis-redeemer", name: "Aegis Redeemer", manufacturer: "Aegis Dynamics", role: "Gunship", size: "Large" },
  { id: "aegis-retaliator", name: "Aegis Retaliator", manufacturer: "Aegis Dynamics", role: "Bomber", size: "Large" },
  { id: "aegis-sabre", name: "Aegis Sabre", manufacturer: "Aegis Dynamics", role: "Stealth Fighter", size: "Small" },
  { id: "aegis-sabre-comet", name: "Aegis Sabre Comet", manufacturer: "Aegis Dynamics", role: "Stealth Fighter", size: "Small" },
  { id: "aegis-vanguard-harbinger", name: "Aegis Vanguard Harbinger", manufacturer: "Aegis Dynamics", role: "Heavy Fighter", size: "Medium" },
  { id: "aegis-vanguard-hoplite", name: "Aegis Vanguard Hoplite", manufacturer: "Aegis Dynamics", role: "Dropship", size: "Medium" },
  { id: "aegis-vanguard-sentinel", name: "Aegis Vanguard Sentinel", manufacturer: "Aegis Dynamics", role: "EWAR", size: "Medium" },
  { id: "aegis-vanguard-warden", name: "Aegis Vanguard Warden", manufacturer: "Aegis Dynamics", role: "Heavy Fighter", size: "Medium" },

  { id: "anvil-arrow", name: "Anvil Arrow", manufacturer: "Anvil Aerospace", role: "Light Fighter", size: "Small" },
  { id: "anvil-ballista", name: "Anvil Ballista", manufacturer: "Anvil Aerospace", role: "Ground AA", size: "Vehicle" },
  { id: "anvil-c8-pisces", name: "Anvil C8 Pisces", manufacturer: "Anvil Aerospace", role: "Shuttle", size: "Small" },
  { id: "anvil-c8x-pisces", name: "Anvil C8X Pisces Expedition", manufacturer: "Anvil Aerospace", role: "Expedition", size: "Small" },
  { id: "anvil-c8r-pisces", name: "Anvil C8R Pisces", manufacturer: "Anvil Aerospace", role: "Rescue", size: "Small" },
  { id: "anvil-carrack", name: "Anvil Carrack", manufacturer: "Anvil Aerospace", role: "Exploration", size: "Capital" },
  { id: "anvil-centurion", name: "Anvil Centurion", manufacturer: "Anvil Aerospace", role: "Ground AA", size: "Vehicle" },
  { id: "anvil-f7c-hornet", name: "Anvil F7C Hornet", manufacturer: "Anvil Aerospace", role: "Medium Fighter", size: "Small" },
  { id: "anvil-f7c-hornet-ghost", name: "Anvil F7C Hornet Ghost", manufacturer: "Anvil Aerospace", role: "Stealth Fighter", size: "Small" },
  { id: "anvil-f7c-hornet-tracker", name: "Anvil F7C Hornet Tracker", manufacturer: "Anvil Aerospace", role: "Recon", size: "Small" },
  { id: "anvil-f7c-super-hornet", name: "Anvil F7C-M Super Hornet", manufacturer: "Anvil Aerospace", role: "Heavy Fighter", size: "Small" },
  { id: "anvil-f7a-mk2", name: "Anvil F7A Mk II", manufacturer: "Anvil Aerospace", role: "Military Fighter", size: "Small" },
  { id: "anvil-hurricane", name: "Anvil Hurricane", manufacturer: "Anvil Aerospace", role: "Heavy Fighter", size: "Small" },
  { id: "anvil-spartan", name: "Anvil Spartan", manufacturer: "Anvil Aerospace", role: "Transport", size: "Vehicle" },
  { id: "anvil-terrapin", name: "Anvil Terrapin", manufacturer: "Anvil Aerospace", role: "Recon", size: "Medium" },
  { id: "anvil-valkyrie", name: "Anvil Valkyrie", manufacturer: "Anvil Aerospace", role: "Dropship", size: "Large" },

  { id: "aopoa-khartu-al", name: "Aopoa Khartu-al", manufacturer: "Aopoa", role: "Scout", size: "Small" },
  { id: "aopoa-nox", name: "Aopoa Nox", manufacturer: "Aopoa", role: "Grav Bike", size: "Vehicle" },
  { id: "aopoa-nox-kue", name: "Aopoa Nox Kue", manufacturer: "Aopoa", role: "Grav Bike", size: "Vehicle" },
  { id: "aopoa-santokyai", name: "Aopoa San'tok.yai", manufacturer: "Aopoa", role: "Medium Fighter", size: "Small" },

  { id: "argo-mole", name: "Argo MOLE", manufacturer: "Argo Astronautics", role: "Mining", size: "Large" },
  { id: "argo-mpuv-cargo", name: "Argo MPUV Cargo", manufacturer: "Argo Astronautics", role: "Utility", size: "Snub" },
  { id: "argo-mpuv-personnel", name: "Argo MPUV Personnel", manufacturer: "Argo Astronautics", role: "Transport", size: "Snub" },
  { id: "argo-raft", name: "Argo RAFT", manufacturer: "Argo Astronautics", role: "Freight", size: "Medium" },
  { id: "argo-srv", name: "Argo SRV", manufacturer: "Argo Astronautics", role: "Tug", size: "Medium" },

  { id: "banu-defender", name: "Banu Defender", manufacturer: "Banu", role: "Escort", size: "Small" },

  { id: "cnou-mustang-alpha", name: "CNOU Mustang Alpha", manufacturer: "Consolidated Outland", role: "Starter", size: "Small" },
  { id: "cnou-mustang-beta", name: "CNOU Mustang Beta", manufacturer: "Consolidated Outland", role: "Pathfinder", size: "Small" },
  { id: "cnou-mustang-delta", name: "CNOU Mustang Delta", manufacturer: "Consolidated Outland", role: "Light Fighter", size: "Small" },
  { id: "cnou-mustang-gamma", name: "CNOU Mustang Gamma", manufacturer: "Consolidated Outland", role: "Racing", size: "Small" },
  { id: "cnou-nomad", name: "CNOU Nomad", manufacturer: "Consolidated Outland", role: "Light Freight", size: "Small" },

  { id: "crusader-a1-spirit", name: "Crusader A1 Spirit", manufacturer: "Crusader Industries", role: "Bomber", size: "Medium" },
  { id: "crusader-c1-spirit", name: "Crusader C1 Spirit", manufacturer: "Crusader Industries", role: "Cargo", size: "Medium" },
  { id: "crusader-a2-hercules", name: "Crusader A2 Hercules", manufacturer: "Crusader Industries", role: "Heavy Bomber", size: "Large" },
  { id: "crusader-c2-hercules", name: "Crusader C2 Hercules", manufacturer: "Crusader Industries", role: "Heavy Cargo", size: "Large" },
  { id: "crusader-m2-hercules", name: "Crusader M2 Hercules", manufacturer: "Crusader Industries", role: "Military Transport", size: "Large" },
  { id: "crusader-mercury-star-runner", name: "Crusader Mercury Star Runner", manufacturer: "Crusader Industries", role: "Data Runner", size: "Large" },

  { id: "drake-buccaneer", name: "Drake Buccaneer", manufacturer: "Drake Interplanetary", role: "Light Fighter", size: "Small" },
  { id: "drake-caterpillar", name: "Drake Caterpillar", manufacturer: "Drake Interplanetary", role: "Cargo", size: "Large" },
  { id: "drake-corsair", name: "Drake Corsair", manufacturer: "Drake Interplanetary", role: "Exploration", size: "Large" },
  { id: "drake-cutter", name: "Drake Cutter", manufacturer: "Drake Interplanetary", role: "Starter", size: "Small" },
  { id: "drake-cutter-rambler", name: "Drake Cutter Rambler", manufacturer: "Drake Interplanetary", role: "Pathfinder", size: "Small" },
  { id: "drake-cutter-scout", name: "Drake Cutter Scout", manufacturer: "Drake Interplanetary", role: "Scout", size: "Small" },
  { id: "drake-cutlass-black", name: "Drake Cutlass Black", manufacturer: "Drake Interplanetary", role: "Medium Freight", size: "Medium" },
  { id: "drake-cutlass-blue", name: "Drake Cutlass Blue", manufacturer: "Drake Interplanetary", role: "Interdiction", size: "Medium" },
  { id: "drake-cutlass-red", name: "Drake Cutlass Red", manufacturer: "Drake Interplanetary", role: "Rescue", size: "Medium" },
  { id: "drake-cutlass-steel", name: "Drake Cutlass Steel", manufacturer: "Drake Interplanetary", role: "Dropship", size: "Medium" },
  { id: "drake-dragonfly-black", name: "Drake Dragonfly Black", manufacturer: "Drake Interplanetary", role: "Grav Bike", size: "Vehicle" },
  { id: "drake-herald", name: "Drake Herald", manufacturer: "Drake Interplanetary", role: "Data Runner", size: "Small" },
  { id: "drake-mule", name: "Drake Mule", manufacturer: "Drake Interplanetary", role: "Utility Vehicle", size: "Vehicle" },
  { id: "drake-vulture", name: "Drake Vulture", manufacturer: "Drake Interplanetary", role: "Salvage", size: "Small" },

  { id: "esperia-blade", name: "Esperia Blade", manufacturer: "Esperia", role: "Light Fighter", size: "Small" },
  { id: "esperia-glaive", name: "Esperia Glaive", manufacturer: "Esperia", role: "Heavy Fighter", size: "Small" },
  { id: "esperia-prowler", name: "Esperia Prowler", manufacturer: "Esperia", role: "Dropship", size: "Medium" },
  { id: "esperia-talon", name: "Esperia Talon", manufacturer: "Esperia", role: "Light Fighter", size: "Small" },
  { id: "esperia-talon-shrike", name: "Esperia Talon Shrike", manufacturer: "Esperia", role: "Missile Fighter", size: "Small" },

  { id: "gatac-syulen", name: "Gatac Syulen", manufacturer: "Gatac", role: "Starter", size: "Small" },

  { id: "greycat-ptv", name: "Greycat PTV", manufacturer: "Greycat Industrial", role: "Rover", size: "Vehicle" },
  { id: "greycat-roc", name: "Greycat ROC", manufacturer: "Greycat Industrial", role: "Mining Vehicle", size: "Vehicle" },
  { id: "greycat-roc-ds", name: "Greycat ROC-DS", manufacturer: "Greycat Industrial", role: "Mining Vehicle", size: "Vehicle" },
  { id: "greycat-stv", name: "Greycat STV", manufacturer: "Greycat Industrial", role: "Buggy", size: "Vehicle" },

  { id: "mirai-fury", name: "Mirai Fury", manufacturer: "Mirai", role: "Snub Fighter", size: "Snub" },
  { id: "mirai-fury-lx", name: "Mirai Fury LX", manufacturer: "Mirai", role: "Racing Snub", size: "Snub" },
  { id: "mirai-fury-mx", name: "Mirai Fury MX", manufacturer: "Mirai", role: "Missile Snub", size: "Snub" },
  { id: "mirai-pulse", name: "Mirai Pulse", manufacturer: "Mirai", role: "Grav Bike", size: "Vehicle" },
  { id: "mirai-pulse-lx", name: "Mirai Pulse LX", manufacturer: "Mirai", role: "Grav Bike", size: "Vehicle" },

  { id: "misc-freelancer", name: "MISC Freelancer", manufacturer: "MISC", role: "Medium Freight", size: "Medium" },
  { id: "misc-freelancer-dur", name: "MISC Freelancer DUR", manufacturer: "MISC", role: "Exploration", size: "Medium" },
  { id: "misc-freelancer-max", name: "MISC Freelancer MAX", manufacturer: "MISC", role: "Freight", size: "Medium" },
  { id: "misc-freelancer-mis", name: "MISC Freelancer MIS", manufacturer: "MISC", role: "Gunship", size: "Medium" },
  { id: "misc-hull-a", name: "MISC Hull A", manufacturer: "MISC", role: "Cargo", size: "Small" },
  { id: "misc-hull-c", name: "MISC Hull C", manufacturer: "MISC", role: "Cargo", size: "Large" },
  { id: "misc-prospector", name: "MISC Prospector", manufacturer: "MISC", role: "Mining", size: "Small" },
  { id: "misc-razor", name: "MISC Razor", manufacturer: "MISC", role: "Racing", size: "Small" },
  { id: "misc-razor-ex", name: "MISC Razor EX", manufacturer: "MISC", role: "Stealth Racing", size: "Small" },
  { id: "misc-razor-lx", name: "MISC Razor LX", manufacturer: "MISC", role: "Racing", size: "Small" },
  { id: "misc-reliant-kore", name: "MISC Reliant Kore", manufacturer: "MISC", role: "Starter", size: "Small" },
  { id: "misc-reliant-mako", name: "MISC Reliant Mako", manufacturer: "MISC", role: "News Van", size: "Small" },
  { id: "misc-reliant-sen", name: "MISC Reliant Sen", manufacturer: "MISC", role: "Science", size: "Small" },
  { id: "misc-reliant-tana", name: "MISC Reliant Tana", manufacturer: "MISC", role: "Light Fighter", size: "Small" },
  { id: "misc-starfarer", name: "MISC Starfarer", manufacturer: "MISC", role: "Refueling", size: "Large" },
  { id: "misc-starfarer-gemini", name: "MISC Starfarer Gemini", manufacturer: "MISC", role: "Military Refueling", size: "Large" },

  { id: "origin-85x", name: "Origin 85X", manufacturer: "Origin Jumpworks", role: "Runabout", size: "Snub" },
  { id: "origin-100i", name: "Origin 100i", manufacturer: "Origin Jumpworks", role: "Starter", size: "Small" },
  { id: "origin-125a", name: "Origin 125a", manufacturer: "Origin Jumpworks", role: "Light Fighter", size: "Small" },
  { id: "origin-135c", name: "Origin 135c", manufacturer: "Origin Jumpworks", role: "Light Freight", size: "Small" },
  { id: "origin-300i", name: "Origin 300i", manufacturer: "Origin Jumpworks", role: "Touring", size: "Small" },
  { id: "origin-315p", name: "Origin 315p", manufacturer: "Origin Jumpworks", role: "Exploration", size: "Small" },
  { id: "origin-325a", name: "Origin 325a", manufacturer: "Origin Jumpworks", role: "Light Fighter", size: "Small" },
  { id: "origin-350r", name: "Origin 350R", manufacturer: "Origin Jumpworks", role: "Racing", size: "Small" },
  { id: "origin-400i", name: "Origin 400i", manufacturer: "Origin Jumpworks", role: "Exploration", size: "Large" },
  { id: "origin-600i-explorer", name: "Origin 600i Explorer", manufacturer: "Origin Jumpworks", role: "Exploration", size: "Large" },
  { id: "origin-600i-touring", name: "Origin 600i Touring", manufacturer: "Origin Jumpworks", role: "Touring", size: "Large" },
  { id: "origin-890-jump", name: "Origin 890 Jump", manufacturer: "Origin Jumpworks", role: "Luxury", size: "Capital" },
  { id: "origin-m50", name: "Origin M50", manufacturer: "Origin Jumpworks", role: "Racing", size: "Small" },
  { id: "origin-x1", name: "Origin X1", manufacturer: "Origin Jumpworks", role: "Grav Bike", size: "Vehicle" },
  { id: "origin-x1-force", name: "Origin X1 Force", manufacturer: "Origin Jumpworks", role: "Grav Bike", size: "Vehicle" },
  { id: "origin-x1-velocity", name: "Origin X1 Velocity", manufacturer: "Origin Jumpworks", role: "Grav Bike", size: "Vehicle" },

  { id: "rsi-aurora-cl", name: "RSI Aurora CL", manufacturer: "RSI", role: "Cargo Starter", size: "Small" },
  { id: "rsi-aurora-es", name: "RSI Aurora ES", manufacturer: "RSI", role: "Starter", size: "Small" },
  { id: "rsi-aurora-ln", name: "RSI Aurora LN", manufacturer: "RSI", role: "Light Fighter", size: "Small" },
  { id: "rsi-aurora-lx", name: "RSI Aurora LX", manufacturer: "RSI", role: "Pathfinder", size: "Small" },
  { id: "rsi-aurora-mr", name: "RSI Aurora MR", manufacturer: "RSI", role: "Starter", size: "Small" },
  { id: "rsi-constellation-andromeda", name: "RSI Constellation Andromeda", manufacturer: "RSI", role: "Gunship", size: "Large" },
  { id: "rsi-constellation-aquila", name: "RSI Constellation Aquila", manufacturer: "RSI", role: "Exploration", size: "Large" },
  { id: "rsi-constellation-phoenix", name: "RSI Constellation Phoenix", manufacturer: "RSI", role: "Touring", size: "Large" },
  { id: "rsi-constellation-taurus", name: "RSI Constellation Taurus", manufacturer: "RSI", role: "Cargo", size: "Large" },
  { id: "rsi-lynx", name: "RSI Lynx", manufacturer: "RSI", role: "Rover", size: "Vehicle" },
  { id: "rsi-mantis", name: "RSI Mantis", manufacturer: "RSI", role: "Interdiction", size: "Small" },
  { id: "rsi-polaris", name: "RSI Polaris", manufacturer: "RSI", role: "Corvette", size: "Capital" },
  { id: "rsi-scorpius", name: "RSI Scorpius", manufacturer: "RSI", role: "Heavy Fighter", size: "Small" },
  { id: "rsi-scorpius-antares", name: "RSI Scorpius Antares", manufacturer: "RSI", role: "Heavy Fighter", size: "Small" },
  { id: "rsi-ursa", name: "RSI Ursa Rover", manufacturer: "RSI", role: "Rover", size: "Vehicle" },
  { id: "rsi-ursa-medivac", name: "RSI Ursa Medivac", manufacturer: "RSI", role: "Medical Rover", size: "Vehicle" },
  { id: "rsi-zeus-cl", name: "RSI Zeus Mk II CL", manufacturer: "RSI", role: "Cargo", size: "Medium" },
  { id: "rsi-zeus-es", name: "RSI Zeus Mk II ES", manufacturer: "RSI", role: "Exploration", size: "Medium" },
  { id: "rsi-zeus-mr", name: "RSI Zeus Mk II MR", manufacturer: "RSI", role: "Bounty Hunting", size: "Medium" },

  { id: "tumbril-cyclone", name: "Tumbril Cyclone", manufacturer: "Tumbril", role: "Rover", size: "Vehicle" },
  { id: "tumbril-cyclone-aa", name: "Tumbril Cyclone AA", manufacturer: "Tumbril", role: "Rover AA", size: "Vehicle" },
  { id: "tumbril-cyclone-mt", name: "Tumbril Cyclone MT", manufacturer: "Tumbril", role: "Rover", size: "Vehicle" },
  { id: "tumbril-cyclone-rn", name: "Tumbril Cyclone RN", manufacturer: "Tumbril", role: "Recon Rover", size: "Vehicle" },
  { id: "tumbril-cyclone-rc", name: "Tumbril Cyclone RC", manufacturer: "Tumbril", role: "Racing Rover", size: "Vehicle" },
  { id: "tumbril-cyclone-tr", name: "Tumbril Cyclone TR", manufacturer: "Tumbril", role: "Rover Turret", size: "Vehicle" },
  { id: "tumbril-nova", name: "Tumbril Nova", manufacturer: "Tumbril", role: "Tank", size: "Vehicle" },
  { id: "tumbril-storm", name: "Tumbril Storm", manufacturer: "Tumbril", role: "Tank", size: "Vehicle" },
  { id: "tumbril-storm-aa", name: "Tumbril Storm AA", manufacturer: "Tumbril", role: "AA Tank", size: "Vehicle" }
];
